name: Hola mundo

on:
    push:
        branches:
              - master
jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola mundo
              run: echo "Hola mundo"
            - name: Instalar figlet
              run: sudo apt-get install figlet
            - name: Usar figlet
              run: figlet "Hola mundo"